language: php
env:
    global:
        - MIN_PHP=7.1.3
php:
  - '7.1'
  - '7.2'
  - '7.3'

install: composer install --prefer-dist

script: phpunit -c ./phpunit.xml.dist

notifications:
  email: false

