language: php
env:
    global:
        - MIN_PHP=7.1.3
php:
  - '7.1'
  - 'nightly'

install: composer install --prefer-dist

#before_script:
  #- mysql -e 'create database orm_test;'

script: phpunit -c ./phpunit.xml.dist

notifications:
  email: false

