<?php

namespace Ordermind\LogicalAuthorizationDoctrineORMBundle\Tests\Fixtures\Repository\User;

/**
 * TestUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestUserRepository extends \Doctrine\ORM\EntityRepository
{
}
