<?php

namespace Ordermind\LogicalAuthorizationDoctrineORMBundle\Tests\Fixtures\Repository\Misc;

/**
 * TestEntityConstructorParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestEntityConstructorParamsRepository extends \Doctrine\ORM\EntityRepository
{

}
