<?php

namespace Ordermind\LogicalAuthorizationDoctrineORMBundle\Tests\Fixtures\Repository\Misc;

/**
 * TestEntityAbortCallsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestEntityAbortCallsRepository extends \Doctrine\ORM\EntityRepository
{
}
