<?php

namespace Ordermind\LogicalAuthorizationDoctrineORMBundle\Tests\Fixtures\Repository\Misc;

/**
 * TestEntityWithParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestEntityWithParamsRepository extends \Doctrine\ORM\EntityRepository
{
    public function customMethod()
    {
        return $this->findAll();
    }
}
